name: Run Python Smart Home App

# Run tests when anything is pushed to the main branch, or a PR to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-python-script:
    # Run on Ubuntu OS
    runs-on: ubuntu-latest

    steps:
        # Download code from GitHub
      - name: Checkout Repository
        uses: actions/checkout@v3

        # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

        # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        # Run the Login Script
      - name: Run Login Script
        run: python main.py

        # Check code quality
      - name: Check Python Code Quality
        run: python -m py_compile main.py

        # Run pytest for tests directory
      - name: Run Pytest
        run: pytest tests/
